#!/usr/bin/python3.5
from os.path import isfile
from sys import argv
from subprocess import PIPE, STDOUT, run

def build(targets):
	for t in targets:
		print("Building %s..."%t)
		proc = run(["/usr/bin/scalac", "Prob%s.scala"%t], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
		if proc.returncode != 0:
			return False
	return True


def exe(targets):
	print("Running...")
	for t in targets:
		proc = run(["/usr/bin/scala", "Prob%s"%t], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
		if proc.returncode == 0 and "Fail" not in proc.stdout:
			print(proc.stdout, end='')
		else:
			return False
	return True

if argv[1] == "clean":
	for i in range(1, 64):
		run(["rm", "-rf", "Prob%d.class"%i])
		run(["rm", "-rf", "Prob%d$.class"%i])
	exit(0)
elif len(argv) < 3:
	print("Missing problem numbers.")

targets = argv[2:]
if targets[0] == "all":
	targets = []
	for i in range(1,64):
		if isfile("Prob%d.scala"%i):
			targets.append(i)

if argv[1] == "run":
	if not exe(targets):
		exit(1)
elif argv[1] == "build":
	if not build(targets):
		exit(1)
elif argv[1] == "buildrun":
	if not (build(targets) and exe(targets)):
		exit(1)
else:
	print("Unrecognized command. Use build or run followed by problems numbers.")
	exit(1)
